apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}
  renewBefore: 48h
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.hostname }}
  dnsNames:
  - {{ .Values.ingress.hostname }}